# Generated by Django 3.0.7 on 2024-04-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20240403_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='google_plus_link',
            new_name='instagram_link',
        ),
    ]
